### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq.data.append_token_dataset'

### ISSUE THREAD

**Issue by Rexbalaeniceps** [xwgeng/RewriteNAT#2]
Hi~ thank you for sharing the codes.

I installed the Dependencies by the following commands:
```bash
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch
cd RewirteNAT
pip install --editable ./
```
following the [Issue 1](https://github.com/xwgeng/RewriteNAT/issues/1), but I got this error when I try to run `preprocess.py`.
```
(rewrite_nat) [wbxu@cu10 RewriteNAT]$ bash preprocess.sh
Traceback (most recent call last):
  File "preprocess.py", line 7, in <module>
    from fairseq_cli.preprocess import cli_main
  File "/data/wbxu/RewriteNAT/fairseq_cli/preprocess.py", line 18, in <module>
    from fairseq import options, tasks, utils
  File "/data/wbxu/RewriteNAT/fairseq/__init__.py", line 9, in <module>
    import fairseq.criterions  # noqa
  File "/data/wbxu/RewriteNAT/fairseq/criterions/__init__.py", line 10, in <module>
    from fairseq.criterions.fairseq_criterion import FairseqCriterion
  File "/data/wbxu/RewriteNAT/fairseq/criterions/fairseq_criterion.py", line 10, in <module>
    from fairseq import metrics, utils
  File "/data/wbxu/RewriteNAT/fairseq/utils.py", line 21, in <module>
    from fairseq.modules import gelu, gelu_accurate
  File "/data/wbxu/RewriteNAT/fairseq/modules/__init__.py", line 9, in <module>
    from .character_token_embedder import CharacterTokenEmbedder
  File "/data/wbxu/RewriteNAT/fairseq/modules/character_token_embedder.py", line 13, in <module>
    from fairseq.data import Dictionary
  File "/data/wbxu/RewriteNAT/fairseq/data/__init__.py", line 12, in <module>
    from .append_token_dataset import AppendTokenDataset
ModuleNotFoundError: No module named 'fairseq.data.append_token_dataset'
```
Could you tell how to deal with this error? Thank you very much~

**Comment by xwgeng** [comment]
I have submitted a new PR to fix above issue. Thanks

**Comment by Rexbalaeniceps** [comment]
Thank you, it works. I will close this issue~
